### ISSUE TITLE
Assert missing file which exists again

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/AvatarManager#7]
https://github.com/laravel-enso/AvatarManager/blob/f75f77d6d17c7dca2013a7625914f0a870314eae/tests/features/AvatarTest.php#L48

core.avatars.update seems to (noticed by debugging) create the updated generation under the same filename as the old one; this causes the test to fail.

**Comment by aocneanu** [comment]
this is how the filename is generated `uniqid(self::Filename.$this->user->id).self::Extension;`. I don't see how it can be the same.

**Comment by aocneanu** [comment]
uniqid generates the id based on the current time in microseconds. I don't see how you can generate the avatar twice, in the same microsecond. But let's change it to something better.
